version: '3.9'

services:
  server:
    build: .
    ports:
      - '4000:5000'
  db:
    image: 'postgres'
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'docker'
    volumes:
      - db-data:/var/lib/postgresql/db-data
  pgadmin:
    image: 'dpage/pgadmin4'
    ports:
      - '1234:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@domain.com'
      PGADMIN_DEFAULT_PASSWORD: '123456'
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data:
